export default [
  {
    login: "Ashish1101",
    id: 41261918,
    node_id: "MDQ6VXNlcjQxMjYxOTE4",
    avatar_url: "https://avatars.githubusercontent.com/u/41261918?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/Ashish1101",
    html_url: "https://github.com/Ashish1101",
    followers_url: "https://api.github.com/users/Ashish1101/followers",
    following_url: "https://api.github.com/users/Ashish1101/following{/other_user}",
    gists_url: "https://api.github.com/users/Ashish1101/gists{/gist_id}",
    starred_url: "https://api.github.com/users/Ashish1101/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/Ashish1101/subscriptions",
    organizations_url: "https://api.github.com/users/Ashish1101/orgs",
    repos_url: "https://api.github.com/users/Ashish1101/repos",
    events_url: "https://api.github.com/users/Ashish1101/events{/privacy}",
    received_events_url: "https://api.github.com/users/Ashish1101/received_events",
    type: "User",
    site_admin: false
  },
  {
    "login": "ashwani65",
    "id": 43879028,
    "node_id": "MDQ6VXNlcjQzODc5MDI4",
    "avatar_url": "https://avatars.githubusercontent.com/u/43879028?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/ashwani65",
    html_url: "https://github.com/ashwani65",
    followers_url: "https://api.github.com/users/ashwani65/followers",
    following_url: "https://api.github.com/users/ashwani65/following{/other_user}",
    gists_url: "https://api.github.com/users/ashwani65/gists{/gist_id}",
    starred_url: "https://api.github.com/users/ashwani65/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/ashwani65/subscriptions",
    organizations_url: "https://api.github.com/users/ashwani65/orgs",
    repos_url: "https://api.github.com/users/ashwani65/repos",
    events_url: "https://api.github.com/users/ashwani65/events{/privacy}",
    received_events_url: "https://api.github.com/users/ashwani65/received_events",
    type: "User",
    site_admin: false
  },
  {
    "login": "anurag-creator",
    "id": 57061821,
    "node_id": "MDQ6VXNlcjU3MDYxODIx",
    "avatar_url": "https://avatars.githubusercontent.com/u/57061821?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/anurag-creator",
    html_url: "https://github.com/anurag-creator",
    followers_url: "https://api.github.com/users/anurag-creator/followers",
    following_url: "https://api.github.com/users/anurag-creator/following{/other_user}",
    gists_url: "https://api.github.com/users/anurag-creator/gists{/gist_id}",
    starred_url: "https://api.github.com/users/anurag-creator/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/anurag-creator/subscriptions",
    organizations_url: "https://api.github.com/users/anurag-creator/orgs",
    repos_url: "https://api.github.com/users/anurag-creator/repos",
    events_url: "https://api.github.com/users/anurag-creator/events{/privacy}",
    received_events_url: "https://api.github.com/users/anurag-creator/received_events",
    type: "User",
    site_admin: false
  }
]