// export default {
//   login: 'gulshanyadav01',
//   id: 42133389,
//   node_id: 'MDQ6VXNlcjQyMTMzMzg5',
//   avatar_url: 'https://avatars3.githubusercontent.com/u/42133389?v=4',
//   gravatar_id: '',
//   url: 'https://api.github.com/users/john-smilga',
//   html_url: 'https://github.com/john-smilga',
//   followers_url: 'https://api.github.com/users/john-smilga/followers',
//   following_url:
//     'https://api.github.com/users/john-smilga/following{/other_user}',
//   gists_url: 'https://api.github.com/users/john-smilga/gists{/gist_id}',
//   starred_url:
//     'https://api.github.com/users/john-smilga/starred{/owner}{/repo}',
//   subscriptions_url: 'https://api.github.com/users/john-smilga/subscriptions',
//   organizations_url: 'https://api.github.com/users/john-smilga/orgs',
//   repos_url: 'https://api.github.com/users/john-smilga/repos',
//   events_url: 'https://api.github.com/users/john-smilga/events{/privacy}',
//   received_events_url:
//     'https://api.github.com/users/john-smilga/received_events',
//   type: 'User',
//   site_admin: false,
//   name: 'John Smilga',
//   company: 'Coding Addict',
//   blog: 'www.johnsmilga.com',
//   location: 'Los Angeles',
//   email: null,
//   hireable: null,
//   bio: 'Creator of Coding Addict',
//   twitter_username: 'john_smilga',
//   public_repos: 152,
//   public_gists: 0,
//   followers: 1495,
//   following: 0,
//   created_at: '2018-08-06T06:48:23Z',
//   updated_at: '2020-07-08T05:01:32Z',
// };


export default {
  login: "gulshanyadav01",
  id: 47187177,
  node_id: "MDQ6VXNlcjQ3MTg3MTc3",
  avatar_url: "https://avatars.githubusercontent.com/u/47187177?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/gulshanyadav01",
  html_url: "https://github.com/gulshanyadav01",
  followers_url: "https://api.github.com/users/gulshanyadav01/followers",
  following_url: "https://api.github.com/users/gulshanyadav01/following{/other_user}",
  gists_url: "https://api.github.com/users/gulshanyadav01/gists{/gist_id}",
  starred_url: "https://api.github.com/users/gulshanyadav01/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/gulshanyadav01/subscriptions",
  organizations_url: "https://api.github.com/users/gulshanyadav01/orgs",
  repos_url: "https://api.github.com/users/gulshanyadav01/repos",
  events_url: "https://api.github.com/users/gulshanyadav01/events{/privacy}",
  received_events_url: "https://api.github.com/users/gulshanyadav01/received_events",
  type: "User",
  site_admin: false,
  name: "gulshan yadav",
  company: null,
  blog: "",
  location: null,
  email: null,
  hireable: null,
  bio: null,
  twitter_username: null,
  public_repos: 68,
  public_gists: 0,
  followers: 3,
  following: 5,
  created_at: "2019-01-30T16:35:55Z",
  updated_at: "2021-07-10T18:58:45Z"
}
